import Head from "next/head";
import Footer from "../components/molecules/Footer";
import Homepage from "./screens/Homepage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Homepage />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
